# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252bdd68289fd5be90fecfccfa0e0ed392e3c288fcf8cc5a3c593e12250c05384f198fd73cfe7c8bf6d5c7c9244daf0fad3a10caf59731d7164a22482b85efd3

test:
  secret_key_base: 4a8ad60c989e0b961a6f68e0b29fe0f4c14e8d4eb98587427adb4c2bc8b646b30d8781631a8257013da45606f2753b09d16631919380a248038eea7f78a18c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
